### Obtiene los blogs de julio
GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bGlvIiwiaWQiOiI2Njg0ZDAzM2U1ZTczNmQyY2NmNTYzZGMiLCJpYXQiOjE3Mjc5MjEyMjl9.LD1O5qSEP9NPi4ZBs5iluN5p_3sgktd_F17aLYx6mdY

### Obtiene los blogs de kelly
GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGx5IiwiaWQiOiI2NmZlODJhYzRmNmM2YWQzZjhjZjhjYTIiLCJpYXQiOjE3Mjc5NTU2NDN9.Vg7VqC1HioYNWCCrwyRuo8lse-1CnShORn_vQnnGCUI