GET http://localhost:3003/api/blogs/testGetTokenFrom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxpbmEiLCJpZCI6IjY2NzFkMTljOWViNDhmNTNmOGNmNGU1MiIsImlhdCI6MTcxOTc1NjU1NH0.6xrMoj52v97BgknDI9hy-FRgpeNrIWANh65vcpxY_2o
